// Generated by scripts/build-runtime.mjs from src/detail/family/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
const STAGES = ["kindergarten", "primary-low", "primary-high", "junior", "senior"];
const STAGE_LABELS = ["\u5E7C\u513F\u56ED", "\u5C0F\u5B66\u4F4E\u5E74\u7EA7", "\u5C0F\u5B66\u9AD8\u5E74\u7EA7", "\u521D\u4E2D", "\u9AD8\u4E2D"];
Page({
  data: { children: [], showForm: false, nickname: "", birthDate: "2018-01-01", stageIndex: 1, saving: false },
  stages: STAGES,
  stageLabels: STAGE_LABELS,
  onLoad() {
    this.refresh();
  },
  async refresh() {
    const children = await import_app.appApi.profile.children();
    this.setData({ children, showForm: false, nickname: "" });
  },
  toggleForm() {
    this.setData({ showForm: !this.data.showForm });
  },
  onNickname(event) {
    this.setData({ nickname: event.detail.value });
  },
  onBirthDate(event) {
    this.setData({ birthDate: event.detail.value });
  },
  onStage(event) {
    this.setData({ stageIndex: Number(event.detail.value) });
  },
  async onSave() {
    if (this.data.saving || this.data.nickname.trim().length === 0) {
      wx.showToast({ title: "\u8BF7\u586B\u5199\u5B69\u5B50\u6635\u79F0", icon: "none" });
      return;
    }
    this.setData({ saving: true });
    const message = await import_app.appApi.profile.saveChild(null, {
      nickname: this.data.nickname.trim(),
      gender: "secret",
      birthDate: this.data.birthDate,
      stage: this.stages[this.data.stageIndex] ?? "primary-low",
      interests: []
    });
    this.setData({ saving: false });
    wx.showToast({ title: message, icon: "none" });
    this.refresh();
  },
  async onRemove(event) {
    await import_app.appApi.profile.removeChild(event.currentTarget.dataset.id);
    this.refresh();
  }
});
