// Generated by scripts/build-runtime.mjs from src/detail/pay/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { order: null, method: "wechat", paying: false },
  onLoad(query) {
    this.refresh(query.orderId ?? "");
  },
  async refresh(orderId) {
    const order = await import_app.appApi.trade.order(orderId);
    this.setData({ order });
  },
  onMethod(event) {
    this.setData({ method: event.currentTarget.dataset.method });
  },
  async onPay() {
    const { order, method, paying } = this.data;
    if (!order || paying) {
      return;
    }
    this.setData({ paying: true });
    const ok = await import_app.appApi.activity.pay(order.id, method);
    this.setData({ paying: false });
    if (ok) {
      wx.showToast({ title: "\u652F\u4ED8\u6210\u529F", icon: "success" });
      wx.redirectTo({ url: `/detail/orders/index?status=upcoming` });
    } else {
      wx.showToast({ title: "\u652F\u4ED8\u5931\u8D25\uFF0C\u8BF7\u91CD\u8BD5", icon: "none" });
    }
  }
});
