// Generated by scripts/build-runtime.mjs from src/pages/login/index.ts — do not edit; edit the .ts source.
Page({
  data: { phone: "", code: "", error: "", submitting: false },
  onLoad() {
    if (wx.getStorageSync("zhiya.session")) {
      wx.switchTab({ url: "/pages/home/index" });
    }
  },
  onPhone(event) {
    this.setData({ phone: event.detail.value });
  },
  onCode(event) {
    this.setData({ code: event.detail.value });
  },
  onSubmit() {
    const phone = this.data.phone.trim();
    const code = this.data.code.trim();
    if (!/^1\d{10}$/u.test(phone)) {
      this.setData({ error: "\u8BF7\u8F93\u5165\u6B63\u786E\u7684 11 \u4F4D\u624B\u673A\u53F7" });
      return;
    }
    if (!/^\d{4,6}$/u.test(code)) {
      this.setData({ error: "\u8BF7\u8F93\u5165 6 \u4F4D\u9A8C\u8BC1\u7801" });
      return;
    }
    this.setData({ error: "", submitting: true });
    wx.setStorageSync("zhiya.session", { phone, nickname: "\u9E2D\u5BB6\u957F" + phone.slice(-4) });
    wx.switchTab({ url: "/pages/home/index" });
  }
});
