// Generated by scripts/build-runtime.mjs from src/detail/coupons/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
const TABS = [
  { id: "claimable", label: "\u53EF\u9886\u53D6" },
  { id: "unused", label: "\u672A\u4F7F\u7528" },
  { id: "used", label: "\u5DF2\u4F7F\u7528" },
  { id: "expired", label: "\u5DF2\u8FC7\u671F" }
];
Page({
  data: { tabs: TABS, tab: "claimable", coupons: [], loading: true },
  onLoad() {
    this.refresh("claimable");
  },
  async refresh(tab) {
    this.setData({ loading: true, tab });
    const coupons = await import_app.appApi.profile.coupons(tab);
    this.setData({ coupons, loading: false });
  },
  onTab(event) {
    this.refresh(event.currentTarget.dataset.id);
  },
  async onClaim(event) {
    const message = await import_app.appApi.profile.claimCoupon(event.currentTarget.dataset.id);
    wx.showToast({ title: message, icon: "none" });
    this.refresh("claimable");
  }
});
