// Generated by scripts/build-runtime.mjs from src/detail/package-detail/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { detail: null, buying: false },
  onLoad(query) {
    this.refresh(query.id ?? "");
  },
  async refresh(id) {
    const detail = await import_app.appApi.activity.packageDetail(id);
    this.setData({ detail });
  },
  goActivity(event) {
    wx.navigateTo({ url: `/detail/activity-detail/index?id=${event.currentTarget.dataset.id}` });
  },
  async onBuy() {
    const { detail, buying } = this.data;
    if (!detail || buying) {
      return;
    }
    this.setData({ buying: true });
    const result = await import_app.appApi.activity.buyPackage(detail.id);
    this.setData({ buying: false });
    if (result.ok && result.orderId) {
      wx.redirectTo({ url: `/detail/pay/index?orderId=${result.orderId}` });
    } else {
      wx.showToast({ title: result.error || "\u4E0B\u5355\u5931\u8D25", icon: "none" });
    }
  }
});
