// Generated by scripts/build-runtime.mjs from src/detail/register/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { pickers: null, childId: "", sessionId: "", couponId: "", submitting: false },
  onLoad(query) {
    this.refresh(query.id ?? "");
  },
  async refresh(id) {
    const pickers = await import_app.appApi.activity.registerPickers(id);
    if (pickers === null) {
      return;
    }
    this.setData({
      pickers,
      childId: pickers.children[0]?.id ?? "",
      sessionId: pickers.sessions[0]?.id ?? ""
    });
  },
  onChild(event) {
    this.setData({ childId: event.currentTarget.dataset.id });
  },
  onSession(event) {
    this.setData({ sessionId: event.currentTarget.dataset.id });
  },
  onCoupon(event) {
    const id = event.currentTarget.dataset.id;
    this.setData({ couponId: this.data.couponId === id ? "" : id });
  },
  async onSubmit() {
    const { pickers, childId, sessionId, couponId, submitting } = this.data;
    if (!pickers || submitting) {
      return;
    }
    if (!childId) {
      wx.showToast({ title: "\u8BF7\u5148\u5230\u300C\u6211\u7684\u5BB6\u5EAD\u300D\u6DFB\u52A0\u5B69\u5B50", icon: "none" });
      return;
    }
    this.setData({ submitting: true });
    const result = await import_app.appApi.activity.createOrder({
      activityId: pickers.activity.id,
      sessionId,
      childId,
      ...couponId ? { couponId } : {}
    });
    this.setData({ submitting: false });
    if (result.ok && result.orderId) {
      wx.redirectTo({ url: `/detail/pay/index?orderId=${result.orderId}` });
    } else {
      wx.showToast({ title: result.error || "\u4E0B\u5355\u5931\u8D25", icon: "none" });
    }
  },
  goFamily() {
    wx.navigateTo({ url: "/detail/family/index" });
  }
});
