// Zhiya 知鸭 mini-program application entry (MINI_PROGRAM_APP_ARCHITECTURE_SPEC.md).
// Authored in TypeScript; src/app.js is generated by scripts/build-runtime.mjs — edit this file instead.
import { appApi } from './runtime/app.js';

App({
  onLaunch() {
    console.log('[zhiya] mini-program launched');
    // 登录门禁 (PRD §3.1 P0): 无会话时进入登录页（mock：任意手机号+6位验证码）。
    const session = wx.getStorageSync('zhiya.session');
    if (!session) {
      wx.reLaunch({ url: '/pages/login/index' });
    }
  },
  globalData: {
    appApi,
  },
});
