// Generated by scripts/build-runtime.mjs from src/app.ts — do not edit; edit the .ts source.
var import_app = require("./runtime/app.js");
App({
  onLaunch() {
    console.log("[zhiya] mini-program launched");
    const session = wx.getStorageSync("zhiya.session");
    if (!session) {
      wx.reLaunch({ url: "/pages/login/index" });
    }
  },
  globalData: {
    appApi: import_app.appApi
  }
});
