// Generated by scripts/build-runtime.mjs from src/detail/benefits/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: {
    orderId: "",
    benefits: [],
    children: [],
    selected: "",
    childId: "",
    sessionId: "",
    error: "",
    submitting: false
  },
  onLoad(query) {
    this.setData({ orderId: query.orderId ?? "" });
    this.refresh();
  },
  async refresh() {
    const benefits = await import_app.appApi.activity.packageBenefits(this.data.orderId);
    const children = await import_app.appApi.profile.children();
    this.setData({ benefits, children });
  },
  onToggle(event) {
    const id = event.currentTarget.dataset.id;
    const benefit = this.data.benefits.find((entry) => entry.activityId === id);
    if (!benefit || benefit.booked) {
      return;
    }
    this.setData({
      selected: this.data.selected === id ? "" : id,
      childId: this.data.childId || (this.data.children[0]?.id ?? ""),
      sessionId: "",
      error: ""
    });
  },
  onChild(event) {
    this.setData({ childId: event.currentTarget.dataset.id });
  },
  onSession(event) {
    this.setData({ sessionId: event.currentTarget.dataset.id });
  },
  async onSubmit() {
    const { orderId, selected, childId, sessionId, submitting } = this.data;
    if (submitting) {
      return;
    }
    if (!childId) {
      this.setData({ error: "\u8BF7\u5148\u5230\u300C\u6211\u7684\u5BB6\u5EAD\u300D\u6DFB\u52A0\u5B69\u5B50" });
      return;
    }
    if (!selected || !sessionId) {
      this.setData({ error: "\u8BF7\u9009\u62E9\u573A\u6B21" });
      return;
    }
    this.setData({ submitting: true, error: "" });
    const result = await import_app.appApi.activity.bookBenefit({ orderId, activityId: selected, sessionId, childId });
    this.setData({ submitting: false });
    if (result.ok) {
      wx.showToast({ title: "\u9884\u7EA6\u6210\u529F", icon: "success" });
      this.refresh();
    } else {
      this.setData({ error: result.error || "\u9884\u7EA6\u5931\u8D25" });
    }
  }
});
