// Generated by scripts/build-runtime.mjs from src/pages/home/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { overview: null, loading: true },
  onLoad() {
    this.refresh();
  },
  async refresh() {
    this.setData({ loading: true });
    const overview = await import_app.appApi.home.overview();
    this.setData({ overview, loading: false });
  },
  goAi() {
    import_app.appApi.shell;
    wx.switchTab({ url: "/pages/ai/index" });
  },
  goActivity() {
    wx.switchTab({ url: "/pages/activity/index" });
  },
  goDetail(event) {
    wx.navigateTo({ url: `/detail/activity-detail/index?id=${event.currentTarget.dataset.id}` });
  },
  goPackage(event) {
    wx.navigateTo({ url: `/detail/package-detail/index?id=${event.currentTarget.dataset.id}` });
  }
});
