// Generated by scripts/build-runtime.mjs from src/pages/mall/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { tabs: [], category: "all", goods: [], loading: true },
  onLoad() {
    this.setData({ tabs: import_app.appApi.shell.goodsCategoryTabs });
    this.refresh("all");
  },
  async refresh(category) {
    this.setData({ loading: true, category });
    const goods = await import_app.appApi.mall.goods(category);
    this.setData({ goods, loading: false });
  },
  onCategory(event) {
    this.refresh(event.currentTarget.dataset.id);
  },
  async onFavorite(event) {
    const id = event.currentTarget.dataset.id;
    await import_app.appApi.mall.toggleFavorite(id);
    wx.showToast({ title: "\u5DF2\u66F4\u65B0\u6536\u85CF", icon: "none" });
  }
});
