// Generated by scripts/build-runtime.mjs from src/detail/messages/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
const CATEGORIES = [
  { id: "all", label: "\u5168\u90E8" },
  { id: "registration", label: "\u62A5\u540D" },
  { id: "payment", label: "\u652F\u4ED8" },
  { id: "refund", label: "\u9000\u6B3E" },
  { id: "coupon", label: "\u4F18\u60E0" },
  { id: "activity", label: "\u6D3B\u52A8" },
  { id: "system", label: "\u7CFB\u7EDF" }
];
Page({
  data: { categories: CATEGORIES, category: "all", messages: [], loading: true },
  onLoad() {
    this.refresh("all");
  },
  async refresh(category) {
    this.setData({ loading: true, category });
    const messages = await import_app.appApi.profile.messages(category);
    this.setData({ messages, loading: false });
  },
  onCategory(event) {
    this.refresh(event.currentTarget.dataset.id);
  },
  async onMarkAll() {
    await import_app.appApi.profile.markAllRead(this.data.category);
    wx.showToast({ title: "\u5DF2\u5168\u90E8\u6807\u8BB0\u5DF2\u8BFB", icon: "none" });
    this.refresh(this.data.category);
  }
});
