// Generated by scripts/build-runtime.mjs from src/pages/activity/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: {
    tabs: [],
    category: "all",
    keyword: "",
    list: [],
    loading: true
  },
  onLoad() {
    this.setData({ tabs: import_app.appApi.shell.categoryTabs });
    this.refresh("all");
  },
  async refresh(category, keyword) {
    const nextKeyword = keyword ?? this.data.keyword;
    this.setData({ loading: true, category });
    const list = await import_app.appApi.activity.list(category, nextKeyword || void 0);
    this.setData({ list, loading: false });
  },
  onKeyword(event) {
    this.setData({ keyword: event.detail.value });
  },
  onSearch() {
    this.refresh(this.data.category, this.data.keyword);
  },
  onCategory(event) {
    this.refresh(event.currentTarget.dataset.id);
  },
  goDetail(event) {
    wx.navigateTo({ url: `/detail/activity-detail/index?id=${event.currentTarget.dataset.id}` });
  }
});
