// Generated by scripts/build-runtime.mjs — do not edit.
module.exports = {
  "environment": "development",
  "deploymentProfile": "standalone",
  "profileId": "standalone.development",
  "runtimeTarget": "mini-program",
  "appApiBaseUrl": "/",
  "sdkBaseUrl": "/"
};
