#!/usr/bin/env node
/**
 * Mini-program runtime bundler (MINI_PROGRAM_APP_ARCHITECTURE_SPEC.md):
 * esbuild-bundles `src/bootstrap/runtime.ts` — plus the whole workspace TS
 * graph behind it — into the committed CommonJS runtime `src/runtime/app.js`,
 * and stamps `src/runtime/runtime-env.js` with the selected profile identity
 * (ENVIRONMENT_SPEC §5.1). Both outputs are committed so WeChat DevTools opens
 * `miniprogramRoot=src/` with no local build.
 *
 * Usage: node scripts/build-runtime.mjs [--deployment-profile standalone] [--environment development] [--watch]
 */

import esbuild from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const flags = {};
for (let index = 2; index < process.argv.length; index += 1) {
  const token = process.argv[index];
  if (token.startsWith('--')) {
    const next = process.argv[index + 1];
    if (next !== undefined && !next.startsWith('--')) {
      flags[token.slice(2)] = next;
      index += 1;
    } else {
      flags[token.slice(2)] = true;
    }
  }
}

const deploymentProfile = flags['deployment-profile'] ?? 'standalone';
const environment = flags.environment ?? 'development';
const profileId = `${deploymentProfile}.${environment}`;

if (deploymentProfile !== 'standalone') {
  console.error(`[zhiya-mp] deployment profile "${deploymentProfile}" is not supported in the standalone milestone.`);
  process.exit(2);
}

const envPath = path.join(appRoot, 'config', 'mini-program', `runtime-env.${profileId}.json`);
let runtimeEnv;
try {
  runtimeEnv = JSON.parse(readFileSync(envPath, 'utf8'));
} catch {
  console.error(`[zhiya-mp] missing runtime-env source: config/mini-program/runtime-env.${profileId}.json`);
  process.exit(2);
}
if (runtimeEnv.profileId !== profileId || runtimeEnv.runtimeTarget !== 'mini-program') {
  console.error(`[zhiya-mp] runtime-env identity mismatch: expected ${profileId}/mini-program`);
  process.exit(2);
}

const outfile = path.join(appRoot, 'src', 'runtime', 'app.js');

/** @returns {Promise<import('esbuild').BuildResult | void>} */
async function build() {
  return esbuild.build({
    entryPoints: [path.join(appRoot, 'src', 'bootstrap', 'runtime.ts')],
    outfile,
    bundle: true,
    format: 'cjs',
    platform: 'neutral',
    target: 'es2021',
    define: {
      __SDKWORK_RUNTIME_ENV__: JSON.stringify(runtimeEnv),
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  });
}

writeFileSync(
  path.join(appRoot, 'src', 'runtime', 'runtime-env.js'),
  `// Generated by scripts/build-runtime.mjs — do not edit.\nmodule.exports = ${JSON.stringify(runtimeEnv, null, 2)};\n`,
);

if (flags.watch === true) {
  const context = await esbuild.context({
    entryPoints: [path.join(appRoot, 'src', 'bootstrap', 'runtime.ts')],
    outfile,
    bundle: true,
    format: 'cjs',
    platform: 'neutral',
    target: 'es2021',
    define: {
      __SDKWORK_RUNTIME_ENV__: JSON.stringify(runtimeEnv),
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  });
  await context.watch();
  console.log('[zhiya-mp] watching for changes…');
} else {
  await build();
  console.log(`[zhiya-mp] runtime bundled for ${profileId} -> src/runtime/app.js`);
}
