#!/usr/bin/env node
/**
 * Mini-program TypeScript builder (MINI_PROGRAM_APP_ARCHITECTURE_SPEC.md §1 language
 * boundary): authored TypeScript is the only source venue in this root.
 *
 * esbuild bundles `src/bootstrap/runtime.ts` — plus the whole workspace TS graph
 * behind it — into the committed CommonJS runtime `src/runtime/app.js`, transpiles
 * every authored page source (`src/app.ts` and each `index.ts` under
 * `src/pages/<page>/` and `src/detail/<page>/`) into its committed platform JS
 * beside it, emits `src/runtime/app.d.ts` so pages consume the typed `PageApi`,
 * and stamps `src/runtime/runtime-env.js` with the selected profile identity
 * (ENVIRONMENT_SPEC §5.1). Every platform `.js` file under `src/` is generated;
 * all outputs are committed so WeChat DevTools opens `miniprogramRoot=src/`
 * with no local build.
 *
 * Usage: node scripts/build-runtime.mjs [--deployment-profile standalone]
 *        [--environment development] [--watch] [--clean]
 */

import esbuild from 'esbuild';
import { existsSync, readdirSync, readFileSync, rmSync, watch, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const flags = {};
for (let index = 2; index < process.argv.length; index += 1) {
  const token = process.argv[index];
  if (token.startsWith('--')) {
    const next = process.argv[index + 1];
    if (next !== undefined && !next.startsWith('--')) {
      flags[token.slice(2)] = next;
      index += 1;
    } else {
      flags[token.slice(2)] = true;
    }
  }
}

const deploymentProfile = flags['deployment-profile'] ?? 'standalone';
const environment = flags.environment ?? 'development';
const profileId = `${deploymentProfile}.${environment}`;

const RUNTIME_OUTPUTS = ['src/runtime/app.js', 'src/runtime/app.d.ts', 'src/runtime/runtime-env.js'];
const PAGE_SOURCE_DIRS = ['pages', 'detail'];

/** Authored page/entry TypeScript sources — the only page authoring venue (spec §1). */
function authoredPageSources() {
  const sources = [];
  const appTs = path.join(appRoot, 'src', 'app.ts');
  if (existsSync(appTs)) {
    sources.push(appTs);
  }
  for (const dir of PAGE_SOURCE_DIRS) {
    const absoluteDir = path.join(appRoot, 'src', dir);
    if (!existsSync(absoluteDir)) {
      continue;
    }
    for (const entry of readdirSync(absoluteDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) {
        continue;
      }
      const pageTs = path.join(absoluteDir, entry.name, 'index.ts');
      if (existsSync(pageTs)) {
        sources.push(pageTs);
      }
    }
  }
  return sources;
}

/** Exact generated-output paths (enumerated, no globs) owned by this tool. */
function generatedOutputs() {
  const outputs = [...RUNTIME_OUTPUTS];
  for (const source of authoredPageSources()) {
    outputs.push(
      path
        .relative(appRoot, source)
        .replaceAll('\\', '/')
        .replace(/\.ts$/u, '.js'),
    );
  }
  return outputs;
}

async function transpilePage(sourcePath) {
  const input = readFileSync(sourcePath, 'utf8');
  const { code } = await esbuild.transform(input, {
    loader: 'ts',
    format: 'cjs',
    target: 'es2021',
    logLevel: 'silent',
  });
  const relative = path.relative(appRoot, sourcePath).replaceAll('\\', '/');
  const banner = `// Generated by scripts/build-runtime.mjs from ${relative} — do not edit; edit the .ts source.\n`;
  writeFileSync(sourcePath.replace(/\.ts$/u, '.js'), `${banner}${code}`);
}

async function transpileAllPages() {
  for (const source of authoredPageSources()) {
    await transpilePage(source);
  }
  const count = authoredPageSources().length;
  console.log(`[zhiya-mp] transpiled ${count} authored TypeScript page sources -> platform JS`);
}

function writeRuntimeTypes() {
  writeFileSync(
    path.join(appRoot, 'src', 'runtime', 'app.d.ts'),
    '// Generated by scripts/build-runtime.mjs — do not edit.\n' +
      "export { appApi } from '../bootstrap/runtime';\n" +
      "export type { PageApi } from '../bootstrap/runtime';\n",
  );
}

function bundleOptions() {
  return {
    entryPoints: [path.join(appRoot, 'src', 'bootstrap', 'runtime.ts')],
    outfile: path.join(appRoot, 'src', 'runtime', 'app.js'),
    bundle: true,
    format: 'cjs',
    platform: 'neutral',
    target: 'es2021',
    banner: {
      js: '// Generated by scripts/build-runtime.mjs — do not edit; edit src/bootstrap/runtime.ts.\n',
    },
    define: {
      __SDKWORK_RUNTIME_ENV__: JSON.stringify(runtimeEnv),
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  };
}

if (flags.clean === true) {
  const outputs = generatedOutputs();
  for (const output of outputs) {
    console.log(`[zhiya-mp] clean: removing generated ${output}`);
    rmSync(path.join(appRoot, output), { force: true });
  }
  process.exit(0);
}

const envPath = path.join(appRoot, 'config', 'mini-program', `runtime-env.${profileId}.json`);
let runtimeEnv;
try {
  runtimeEnv = JSON.parse(readFileSync(envPath, 'utf8'));
} catch {
  console.error(`[zhiya-mp] missing runtime-env source: config/mini-program/runtime-env.${profileId}.json`);
  process.exit(2);
}
if (runtimeEnv.profileId !== profileId || runtimeEnv.runtimeTarget !== 'mini-program') {
  console.error(`[zhiya-mp] runtime-env identity mismatch: expected ${profileId}/mini-program`);
  process.exit(2);
}

writeFileSync(
  path.join(appRoot, 'src', 'runtime', 'runtime-env.js'),
  `// Generated by scripts/build-runtime.mjs — do not edit.\nmodule.exports = ${JSON.stringify(runtimeEnv, null, 2)};\n`,
);
writeRuntimeTypes();

if (flags.watch === true) {
  await transpileAllPages();
  const context = await esbuild.context(bundleOptions());
  await context.watch();
  const srcWatcher = watch(path.join(appRoot, 'src'), { recursive: true }, (_event, filename) => {
    if (!filename) {
      return;
    }
    const normalized = String(filename).replaceAll('\\', '/');
    if (!normalized.endsWith('.ts') || normalized.startsWith('runtime/') || normalized.startsWith('bootstrap/')) {
      return;
    }
    const absolute = path.join(appRoot, 'src', normalized);
    if (existsSync(absolute)) {
      transpilePage(absolute).catch((error) => {
        console.error(`[zhiya-mp] page transpile failed for ${normalized}:`, error.message);
      });
    }
  });
  const stopWatching = () => {
    srcWatcher.close();
    context.dispose();
  };
  process.on('SIGINT', () => {
    stopWatching();
    process.exit(0);
  });
  console.log('[zhiya-mp] watching for changes…');
} else {
  await transpileAllPages();
  await esbuild.build(bundleOptions());
  console.log(`[zhiya-mp] runtime bundled for ${profileId} -> src/runtime/app.js`);
}
