// Generated by scripts/build-runtime.mjs from src/pages/profile/index.ts — do not edit; edit the .ts source.
Page({
  data: { entries: [] },
  onLoad() {
    this.setData({
      entries: [
        { key: "family", glyph: "\u{1F476}", title: "\u6211\u7684\u5BB6\u5EAD", desc: "\u7BA1\u7406\u5B69\u5B50\u8D44\u6599", url: "/detail/family/index" },
        { key: "orders", glyph: "\u{1F4CB}", title: "\u6211\u7684\u8BA2\u5355", desc: "\u62A5\u540D / \u4F53\u9A8C\u5305 / \u9000\u6B3E", url: "/detail/orders/index" },
        { key: "coupons", glyph: "\u{1F39F}\uFE0F", title: "\u4F18\u60E0\u5238", desc: "\u9886\u5238\u4E2D\u5FC3 / \u6211\u7684\u5361\u5305", url: "/detail/coupons/index" },
        { key: "messages", glyph: "\u{1F514}", title: "\u6D88\u606F\u4E2D\u5FC3", desc: "\u62A5\u540D\u3001\u652F\u4ED8\u3001\u4F18\u60E0\u901A\u77E5", url: "/detail/messages/index" }
      ]
    });
  },
  go(event) {
    wx.navigateTo({ url: event.currentTarget.dataset.url });
  },
  goActivity() {
    wx.switchTab({ url: "/pages/activity/index" });
  }
});
