/**
 * Mini-program surface contract tests (TEST_SPEC.md §2.4.2,
 * MINI_PROGRAM_APP_ARCHITECTURE_SPEC.md verification): manifest ↔ pages
 * alignment, page-file completeness, runtime-bundle freshness/profile stamp,
 * the wx.* host-adapter boundary, and cross-surface route alignment.
 * Pure Node — no WeChat tooling required.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function readJson(relative) {
  return JSON.parse(readFileSync(path.join(appRoot, relative), 'utf8'));
}

function listFiles(relativeDir) {
  const absolute = path.join(appRoot, relativeDir);
  if (!existsSync(absolute)) return [];
  return readdirSync(absolute, { recursive: true })
    .map((entry) => path.join(relativeDir, String(entry)).replaceAll('\\', '/'))
    .filter((file) => statSync(path.join(appRoot, file)).isFile());
}

function existsSync(relative) {
  try {
    statSync(path.join(appRoot, relative));
    return true;
  } catch {
    return false;
  }
}

const TAB_IDS = ['home', 'activity', 'ai', 'mall', 'profile'];
const TAB_LABELS = ['首页', '活动', 'AI', '商城', '我的'];
const DETAIL_PAGES = [
  'detail/activity-detail/index',
  'detail/register/index',
  'detail/pay/index',
  'detail/orders/index',
  'detail/review/index',
  'detail/family/index',
  'detail/messages/index',
  'detail/coupons/index',
  'detail/package-detail/index',
  'detail/benefits/index',
];

describe('zhiya mini-program surface contract', () => {
  it('app_json_projects_exactly_the_five_tab_pages_and_the_detail_subpackage', () => {
    const appJson = readJson('src/app.json');
    const expectedPages = ['pages/login/index', ...TAB_IDS.map((id) => `pages/${id}/index`)];
    assert.deepEqual(appJson.pages, expectedPages);
    assert.equal(appJson.subPackages.length, 1);
    assert.equal(appJson.subPackages[0].root, 'detail');
    assert.deepEqual(appJson.subPackages[0].pages, DETAIL_PAGES.map((page) => page.replace('detail/', '')));
    assert.equal(appJson.tabBar.list.length, 5);
    assert.deepEqual(
      appJson.tabBar.list.map((entry) => entry.text),
      TAB_LABELS,
    );
    for (const page of expectedPages) {
      if (page === 'pages/login/index') {
        // 登录是非 tabBar 入口页（冷启动门禁）。
        continue;
      }
      assert.ok(
        appJson.tabBar.list.some((entry) => entry.pagePath === page),
        `tab page ${page} missing from tabBar`,
      );
    }
  });

  it('every_declared_page_has_a_complete_index_quad', () => {
    const appJson = readJson('src/app.json');
    const declared = [
      ...appJson.pages,
      ...appJson.subPackages.flatMap((pkg) => pkg.pages.map((page) => `${pkg.root}/${page}`)),
    ].map((page) => `src/${page}`);
    for (const page of declared) {
      for (const ext of ['js', 'json', 'wxml', 'wxss']) {
        assert.ok(existsSync(`${page}.${ext}`), `missing ${page}.${ext}`);
      }
    }
  });

  it('every_page_source_is_typescript_and_platform_js_is_generated', () => {
    // MINI_PROGRAM_APP_ARCHITECTURE_SPEC.md §1 language boundary: authored sources
    // are .ts; platform .js beside them must carry the generated banner.
    const appJson = readJson('src/app.json');
    const declared = [
      ...appJson.pages,
      ...appJson.subPackages.flatMap((pkg) => pkg.pages.map((page) => `${pkg.root}/${page}`)),
    ].map((page) => `src/${page}`);
    assert.ok(existsSync('src/app.ts'), 'missing authored src/app.ts');
    for (const page of declared) {
      assert.ok(existsSync(`${page}.ts`), `missing authored ${page}.ts`);
      const js = readFileSync(path.join(appRoot, `${page}.js`), 'utf8');
      assert.match(js, /^\/\/ Generated by scripts\/build-runtime\.mjs/u, `${page}.js must be generated output`);
    }
    for (const generated of ['src/app.js', 'src/runtime/app.js', 'src/runtime/app.d.ts', 'src/runtime/runtime-env.js']) {
      assert.ok(existsSync(generated), `missing generated ${generated} — run \`pnpm build\``);
    }
    const runtimeTypes = readFileSync(path.join(appRoot, 'src/runtime/app.d.ts'), 'utf8');
    assert.ok(runtimeTypes.includes('PageApi'), 'runtime app.d.ts must expose the typed PageApi');
  });

  it('tsconfig_keeps_the_strict_family_over_the_whole_authored_graph', () => {
    // TYPESCRIPT_CODE_SPEC.md §1 baseline: strict plus the extended strict family.
    const tsconfig = readJson('tsconfig.json');
    for (const flag of [
      'strict',
      'noImplicitAny',
      'strictNullChecks',
      'noUncheckedIndexedAccess',
      'exactOptionalPropertyTypes',
      'noImplicitReturns',
      'noFallthroughCasesInSwitch',
    ]) {
      assert.equal(tsconfig.compilerOptions[flag], true, `tsconfig must keep ${flag}`);
    }
    for (const required of [
      'src/app.ts',
      'src/bootstrap/**/*.ts',
      'src/pages/**/*.ts',
      'src/detail/**/*.ts',
      'packages/*/src/**/*.ts',
    ]) {
      assert.ok(tsconfig.include.includes(required), `tsconfig include must cover ${required}`);
    }
  });

  it('runtime_bundle_exists_and_is_profile_stamped', () => {
    const bundle = readFileSync(path.join(appRoot, 'src/runtime/app.js'), 'utf8');
    assert.ok(bundle.length > 1000, 'runtime bundle too small — run `pnpm build`');
    const stampSource = readFileSync(path.join(appRoot, 'src/runtime/runtime-env.js'), 'utf8');
    const moduleMatch = /module\.exports\s*=\s*(\{[\s\S]*\});\s*$/u.exec(stampSource);
    assert.ok(moduleMatch, 'runtime-env.js must end with module.exports = {...}');
    const stamp2 = JSON.parse(moduleMatch[1]);
    assert.equal(stamp2.runtimeTarget, 'mini-program');
    assert.match(stamp2.profileId, /^(standalone|cloud)\.(development|test|staging|production)$/u);
  });

  it('capability_packages_never_call_wx_directly_host_adapter_boundary', () => {
    const packagesRoot = path.join(appRoot, 'packages');
    for (const pkg of readdirSync(packagesRoot)) {
      const indexSource = readFileSync(path.join(packagesRoot, pkg, 'src', 'index.ts'), 'utf8');
      const withoutComments = indexSource.replace(/\/\*[\s\S]*?\*\//gu, '').replace(/^\s*\/\/.*$/gmu, '');
      assert.doesNotMatch(withoutComments, /\bwx\.[a-z]/u, `${pkg} must not call wx.* directly`);
    }
  });

  it('route_projection_stays_aligned_with_the_cross_surface_tabs', () => {
    const shell = readFileSync(path.join(appRoot, 'packages/sdkwork-zhiya-mp-shell/src/index.ts'), 'utf8');
    for (const id of TAB_IDS) {
      assert.ok(shell.includes(`pages/${id}/index`), `shell projection missing pages/${id}/index`);
    }
    const routeCore = readFileSync(
      path.join(appRoot, '../sdkwork-zhiya-common/packages/sdkwork-zhiya-route-core/src/tabs.ts'),
      'utf8',
    );
    for (const label of TAB_LABELS) {
      assert.ok(routeCore.includes(label), `route-core tab contract missing ${label}`);
    }
  });
});
