// Generated by scripts/build-runtime.mjs from src/detail/review/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
const DIMENSIONS = ["overall", "experience", "teacher", "environment", "service"];
const LABELS = {
  overall: "\u7EFC\u5408\u8BC4\u5206",
  experience: "\u6D3B\u52A8\u4F53\u9A8C",
  teacher: "\u6559\u5E08",
  environment: "\u73AF\u5883",
  service: "\u670D\u52A1"
};
Page({
  data: {
    dimensions: DIMENSIONS.map((id) => ({ id, label: LABELS[id], score: 5 })),
    scores: { overall: 5, experience: 5, teacher: 5, environment: 5, service: 5 },
    recommend: true,
    content: "",
    orderId: "",
    submitting: false
  },
  onLoad(query) {
    this.setData({ orderId: query.orderId ?? "" });
  },
  onScore(event) {
    const { dimension, value } = event.currentTarget.dataset;
    const score = Number(value);
    const dimensions = this.data.dimensions.map(
      (entry) => entry.id === dimension ? { ...entry, score } : entry
    );
    const scores = { ...this.data.scores, [dimension]: score };
    this.setData({ dimensions, scores });
  },
  onRecommend() {
    this.setData({ recommend: !this.data.recommend });
  },
  onContent(event) {
    this.setData({ content: event.detail.value });
  },
  async onSubmit() {
    if (this.data.submitting) {
      return;
    }
    this.setData({ submitting: true });
    const message = await import_app.appApi.trade.submitReview(this.data.orderId, {
      ...this.data.scores,
      recommend: this.data.recommend,
      content: this.data.content
    });
    this.setData({ submitting: false });
    wx.showToast({ title: message, icon: "none" });
    if (message.indexOf("\u6210\u529F") >= 0) {
      wx.navigateBack();
    }
  }
});
