// Generated by scripts/build-runtime.mjs from src/detail/orders/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { tabs: [], status: "all", orders: [], loading: true },
  onLoad(query) {
    this.setData({ tabs: import_app.appApi.shell.orderStatusTabs });
    this.refresh(query.status ?? "all");
  },
  async refresh(status) {
    this.setData({ loading: true, status });
    const orders = await import_app.appApi.trade.orders(status);
    this.setData({ orders, loading: false });
  },
  onStatus(event) {
    this.refresh(event.currentTarget.dataset.id);
  },
  async onAction(event) {
    const { id, action } = event.currentTarget.dataset;
    const message = await import_app.appApi.trade.action(id, action);
    wx.showToast({ title: message, icon: "none" });
    this.refresh(this.data.status);
  },
  goReview(event) {
    wx.navigateTo({ url: `/detail/review/index?orderId=${event.currentTarget.dataset.id}` });
  },
  goPay(event) {
    wx.redirectTo({ url: `/detail/pay/index?orderId=${event.currentTarget.dataset.id}` });
  },
  goBenefits(event) {
    wx.navigateTo({ url: `/detail/benefits/index?orderId=${event.currentTarget.dataset.id}` });
  }
});
