// Generated by scripts/build-runtime.mjs from src/detail/activity-detail/index.ts — do not edit; edit the .ts source.
var import_app = require("../../runtime/app.js");
Page({
  data: { detail: null },
  onLoad(query) {
    this.refresh(query.id ?? "");
  },
  async refresh(id) {
    const detail = await import_app.appApi.activity.detail(id);
    this.setData({ detail });
  },
  goRegister() {
    const { detail } = this.data;
    if (!detail || detail.remaining === 0) {
      return;
    }
    wx.navigateTo({ url: `/detail/register/index?id=${detail.id}` });
  }
});
